import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpParams } from '@angular/common/http';
import { catchError, map, Observable, tap, throwError } from 'rxjs';
import { environment } from '../../../../../environments/environment.development';
import { AuthService } from '../../../../core/services/auth/auth.service';
import { IOffer } from '../../interfaces/ioffer';
import {
  ArrayApiResponse,
  ObjectApiResponse,
} from '../../../../core/interfaces/ApiResponse';
import { IOfferProfile } from '../../interfaces/IOfferProfile';

@Injectable({
  providedIn: 'root',
})
export class OfferService {
  private createOfferUrl: string = `${environment.baseApi}${environment.offer.create}`;
  private getOffersUrl: string = `${environment.baseApi}${environment.offer.getAllForCurrentUser}`;

  constructor(private http: HttpClient, private auth: AuthService) {}

  /**
   * Create a new offer for a project
   * @param offer an IOffer object (id can be omitted or generated by the server)
   */
  createOffer(offer: IOffer): Observable<IOffer> {
    return this.http
      .post<ObjectApiResponse<IOffer>>(this.createOfferUrl, offer)
      .pipe(
        map((resp) => {
          if (!resp.isValid) {
            throw new Error(resp.errorMessage || 'Failed to create offer');
          }
          return resp.data;
        })
      );
  }

  /** fetch all offers made by the logged-in user */
  getCurrentUserOffers(): Observable<IOffer[]> {
    return this.http.get<ArrayApiResponse<IOffer>>(this.getOffersUrl).pipe(
      map((resp) => {
        if (!resp.isValid) {
          throw new Error(resp.errorMessage || 'Failed to load offers');
        }
        return resp.data;
      })
    );
  }

  getOfferforProject(projectId: number): Observable<IOfferProfile[]> {
    const path = environment.offer.getOfferByProjectId(projectId);
    const url = `${environment.baseApi}${path}`;
    return this.http
      .get<ArrayApiResponse<IOfferProfile>>(url)
      .pipe(
        map(resp => {
          if (!resp.isValid) {
            throw new Error(resp.errorMessage || 'Failed to load offers by project');
          }
          return resp.data;
        })
      );
  }
  
  changeOfferStatus(offerId: number, status: 'Accepted' | 'Rejected'): Observable<IOfferProfile> {
    const url = `${environment.baseApi}${environment.offer.BusinessOwnerAnswer(offerId)}`;
  
    // Build the query string
    const params = new HttpParams().set('status', status);
  
    return this.http
      // send `null` as the body
      .post<ObjectApiResponse<IOfferProfile>>(url, null, { params, observe: 'response' })
      .pipe(
        tap(fullResp => console.log('✔️ 200 OK, body:', fullResp.body)),
        map(resp => {
          if (!resp.body!.isValid) {
            throw new Error(resp.body!.errorMessage || 'Failed to change offer status');
          }
          return resp.body!.data;
        }),
        catchError((err: HttpErrorResponse) => {
          console.error(`❌ ${err.status} Error`, err.error);
          return throwError(() => err);
        })
      );
  }
}
